USE {YOUR_DATABASE};

DROP TABLE IF EXISTS covid;

CREATE EXTERNAL TABLE covid(log_date STRING, county STRING, new_positive INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE
LOCATION '{YOUR_COVID_OUTPUT_PATH_1}';
