-- CONNECT TO DATABASE
USE {YOUR_DATABASE};

-- CREATE EXTERNAL TABLE mta
CREATE EXTERNAL TABLE mta(log_date STRING, new_riders INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE
LOCATION 'output/mta/mta';
